// Copyright (c) 2026 CCI Volunteer Legion and ATLNO.exe.
// Generates public runtime workbook feed config from environment values.

import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

const root = new URL("../", import.meta.url);
const envLocalUrl = new URL(".env.local", root);
const outputUrl = new URL("src/data/sheet-config.js", root);
const defaults = {
  PUBLIC_GOOGLE_SHEET_WORKBOOK_ID:
    "2PACX-1vSs11px-8Fl8S-FvFYdg_lx-ep4mxx0RGzXi54s5kmEFGsc95UW3i5Nxrc63SzrsmOK0gd_5uJivxOQ",
  PUBLIC_TITAN_GID: "1994318444",
  PUBLIC_NEXUS_GID: "612483539",
  PUBLIC_DOMINION_GID: "945411688",
  PUBLIC_WILDCARD_GID: "1564963263",
  PUBLIC_FINALS_GID: "126700734",
  PUBLIC_SHEET_CACHE_MS: "120000",
  PUBLIC_SHEET_AUTO_REFRESH_MS: "120000",
  PUBLIC_SHEET_TIMEOUT_MS: "8000",
  PUBLIC_SHEET_SOURCE_LABEL: "Google Sheet",
};

const env = {
  ...defaults,
  ...process.env,
  ...(await readLocalEnv(envLocalUrl)),
};

const workbookId = required(env.PUBLIC_GOOGLE_SHEET_WORKBOOK_ID, "PUBLIC_GOOGLE_SHEET_WORKBOOK_ID");
if (!/^[A-Za-z0-9_-]+$/.test(workbookId)) {
  fail(
    "PUBLIC_GOOGLE_SHEET_WORKBOOK_ID must be the published workbook id from the /d/e/<id>/ URL.",
  );
}

const cacheMs = parsePositiveInteger(env.PUBLIC_SHEET_CACHE_MS, "PUBLIC_SHEET_CACHE_MS");
const autoRefreshMs = parsePositiveInteger(
  env.PUBLIC_SHEET_AUTO_REFRESH_MS,
  "PUBLIC_SHEET_AUTO_REFRESH_MS",
);
const timeoutMs = parsePositiveInteger(env.PUBLIC_SHEET_TIMEOUT_MS, "PUBLIC_SHEET_TIMEOUT_MS");
const sourceLabel = env.PUBLIC_SHEET_SOURCE_LABEL?.trim() || defaults.PUBLIC_SHEET_SOURCE_LABEL;
const gids = {
  titan: requiredGid(env.PUBLIC_TITAN_GID, "PUBLIC_TITAN_GID"),
  nexus: requiredGid(env.PUBLIC_NEXUS_GID, "PUBLIC_NEXUS_GID"),
  dominion: requiredGid(env.PUBLIC_DOMINION_GID, "PUBLIC_DOMINION_GID"),
  wildcard: requiredGid(env.PUBLIC_WILDCARD_GID, "PUBLIC_WILDCARD_GID"),
  finals: requiredGid(env.PUBLIC_FINALS_GID, "PUBLIC_FINALS_GID"),
};

const content = `// Copyright (c) 2026 CCI Volunteer Legion and ATLNO.exe.
// Public event data is loaded only from published public workbook tabs.
// Generated by scripts/configure-sheet.mjs.

const workbookId = ${JSON.stringify(workbookId)};
const publishedCsvUrl = (gid) => {
  return \`https://docs.google.com/spreadsheets/d/e/\${workbookId}/pub?single=true&output=csv&gid=\${gid}\`;
};

export const sheetConfig = {
  enabled: true,
  sourceLabel: ${JSON.stringify(sourceLabel)},
  workbookId,
  cacheKey: "cci-legion-wars:workbook-feeds:v2",
  minFetchIntervalMs: ${cacheMs},
  autoRefreshIntervalMs: ${autoRefreshMs},
  requestTimeoutMs: ${timeoutMs},
  feeds: [
    {
      id: "national-finals",
      label: "National Finals",
      shortLabel: "Finals",
      type: "finals",
      gid: ${JSON.stringify(gids.finals)},
      csvUrl: publishedCsvUrl(${JSON.stringify(gids.finals)}),
      summary: "16-player national final bracket: 12 direct group qualifiers plus 4 wildcard qualifiers.",
      finalistSlots: 16
    },
    {
      id: "group-titan",
      label: "Group Titan Bracket",
      shortLabel: "Titan",
      type: "group",
      gid: ${JSON.stringify(gids.titan)},
      csvUrl: publishedCsvUrl(${JSON.stringify(gids.titan)}),
      summary: "Top 4 advance directly to National Finals; 5th-8th enter Wildcard."
    },
    {
      id: "group-nexus",
      label: "Group Nexus Bracket",
      shortLabel: "Nexus",
      type: "group",
      gid: ${JSON.stringify(gids.nexus)},
      csvUrl: publishedCsvUrl(${JSON.stringify(gids.nexus)}),
      summary: "Top 4 advance directly to National Finals; 5th-8th enter Wildcard."
    },
    {
      id: "group-dominion",
      label: "Group Dominion Bracket",
      shortLabel: "Dominion",
      type: "group",
      gid: ${JSON.stringify(gids.dominion)},
      csvUrl: publishedCsvUrl(${JSON.stringify(gids.dominion)}),
      summary: "Top 4 advance directly to National Finals; 5th-8th enter Wildcard."
    },
    {
      id: "wildcard",
      label: "Wildcard",
      shortLabel: "Wildcard",
      type: "wildcard",
      gid: ${JSON.stringify(gids.wildcard)},
      csvUrl: publishedCsvUrl(${JSON.stringify(gids.wildcard)}),
      summary: "Wildcard produces 4 National Finals qualifiers."
    }
  ]
};
`;

await writeFile(outputUrl, content, "utf8");
console.log(`Wrote ${filePath(outputUrl)}`);

async function readLocalEnv(url) {
  if (!existsSync(url)) return {};
  const text = await readFile(url, "utf8");
  const values = {};

  text.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;

    const equalsIndex = trimmed.indexOf("=");
    if (equalsIndex === -1) return;

    const key = trimmed.slice(0, equalsIndex).trim();
    const rawValue = trimmed.slice(equalsIndex + 1).trim();
    values[key] = stripQuotes(rawValue);
  });

  return values;
}

function stripQuotes(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

function required(value, label) {
  const text = value?.trim();
  if (!text) fail(`${label} is required.`);
  return text;
}

function requiredGid(value, label) {
  const text = required(value, label);
  if (!/^\d+$/.test(text)) fail(`${label} must be a numeric public sheet gid.`);
  return text;
}

function parsePositiveInteger(value, label) {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    fail(`${label} must be a positive integer.`);
  }
  return parsed;
}

function fail(message) {
  console.error(message);
  process.exit(1);
}

function filePath(url) {
  return decodeURIComponent(url.pathname).replace(/^\/([A-Za-z]:\/)/, "$1");
}
